version: "3.7"
services:
    
    nginx:
        image: nginx:latest
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./conf/nginx:/etc/nginx/conf.d
            - ./logs/nginx:/var/logs/nginx
            - ./apps:/var/www/html
        depends_on:
            - php
        restart: always
        
    php:
        build: ./php
        volumes:
            - ./apps:/var/www/html
        restart: always
        depends_on:
            - mysql

    mysql:
        image: mariadb
        ports:
            - '3306:3306'
        volumes:
            - ./dbdata:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        restart: always
